### ISSUE TITLE
Nepredvidatelny pad

### ISSUE THREAD

**Issue by lukyrys** [Chatujme/ChatujmeGW#1]
Zjistit proc a opravit

```
Traceback (most recent call last):
  File "c:\users\LukßÜ\ownCloud\Chatujme\Chatujme - Vřvoj\ChatujmeGW\chatujmegw.py", line 633, in run
    if (instance.parse(ircdata,timestamp) == 2):
  File "c:\users\LukßÜ\ownCloud\Chatujme\Chatujme - Vřvoj\ChatujmeGW\chatujmegw.py", line 491, in parse
    getusers = self.getRoomUsers( room.id )
  File "c:\users\LukßÜ\ownCloud\Chatujme\Chatujme - Vřvoj\ChatujmeGW\chatujmegw.py", line 359, in getRoomUsers
    response = self.getUrl( "%s/%s?id=%s" %(self.system.url, "get-users", room_id) )
  File "c:\users\LukßÜ\ownCloud\Chatujme\Chatujme - Vřvoj\ChatujmeGW\chatujmegw.py", line 292, in getUrl
    response = self.user.urlfetcher.open(url)
  File "c:\Python27\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "c:\Python27\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "c:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "c:\Python27\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10060] Pokus o p°ipojenÝ selhal, proto×e p°ipojenß strana v ŔasovÚm intervalu °ßdný neodpovýdýla, nebo vytvo°enÚ p°ipojenÝ selhalo, proto×e neodpovýdýl p°ipojenř hostitel>    
```

**Comment by lukyrys** [comment]
#17
