### ISSUE TITLE
timeout pri odesilani zpravy na server sunda pripojeni

### ISSUE THREAD

**Issue by hkrbrps** [Chatujme/ChatujmeGW#16]
```
[2016/01/26 17:26:03] Spojeni z 127.0.0.1 uzavreno.                                                                                                                            
Traceback (most recent call last):                                                                                                                                             
  File "chatujmegw.py", line 876, in run                                                                                                                                       
    if (instance.parse(ircdata,timestamp) == 2):                                                                                                                               
  File "chatujmegw.py", line 750, in parse                                                                                                                                     
    data = self.sendText( msg, roomId, cmd[1] )                                                                                                                                
  File "chatujmegw.py", line 550, in sendText                                                                                                                                  
    response = self.postUrl( "%s/%s" %(self.system.url, "post-text"), postdata )                                                                                               
  File "chatujmegw.py", line 441, in postUrl                                                                                                                                   
    response = self.user.urlfetcher.open(url , data=postdata)                                                                                                                  
  File "/usr/lib/python2.7/urllib2.py", line 401, in open                                                                                                                      
    response = self._open(req, data)                                                                                                                                           
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open                                                                                                                     
    '_open', req)                                                                                                                                                              
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain                                                                                                               
    result = func(*args)                                                                                                                                                       
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open                                                                                                                
    return self.do_open(httplib.HTTPConnection, req)                                                                                                                           
  File "/usr/lib/python2.7/urllib2.py", line 1181, in do_open                                                                                                                  
    raise URLError(err)                                                                                                                                                        
URLError: <urlopen error [Errno 110] Connection timed out>                                                                                                                     
[2016/01/26 17:26:03] SENDING: None -> :OptiBot PART #20404 :                                                                                                                  

^CTraceback (most recent call last):                                                                                                                                           
  File "chatujmegw.py", line 927, in <module>                                                                                                                                  
    log("Vypinam...", 1)                                                                                                                                                       
TypeError: log() takes exactly 1 argument (2 given)                                                                                                                            
[2016/01/26 17:27:49] collector, shutdown                                  
```

**Comment by lukyrys** [comment]
Duplicitniu #17
